### ISSUE TITLE
Since switching to createRoute (concurrent React), inline styles are sometimes not updated

### ISSUE THREAD

**Issue by adrienharnay** [roginfarrer/collapsed#103]
Hello,

Since switching to React 18 and `react-dom/client`'s `createRoute`, when I try to open the Collapse (passing `isExpanded: true` to `getCollapseProps`) after the first render the inline styles don't get updated: https://gyazo.com/9c552baad3819a12908c12a85288e223. I need to set `isExpanded` to false, and then to true for the inline styles to be correct.

I don't have this issue with `React.render` (non-concurrent React API).

Thanks in advance and have a great day!

**Comment by adrienharnay** [comment]
Reverting to 3.3.2 (without #98) fixes the issue. Any idea how upgrading and using React's `useId` could generate this bug? cc. @gaearon @roginfarrer

**Comment by adrienharnay** [comment]
OK so I tested again after adding logs everywhere to try and understand the root cause. It would seem that when the bug occurs, the `onTransitionEnd` handler passed to the child element is not called by React... 🫠 Is it a side-effect or the root cause?

**Comment by roginfarrer** [comment]
Meant to release at v4@next, but couldn't figure out the magic words for semantic-release 🤷🏻. Can you try testing with `react-collapsed@next` @adrienharnay?

**Comment by adrienharnay** [comment]
Hello, sorry for the delay. I just tested and got the `useId` is not a function error

<img width="587" alt="Screenshot 2022-12-12 at 08 39 04" src="https://user-images.githubusercontent.com/15089053/206988563-3369093c-5b53-40d3-b793-f0cf9418ab5b.png">

Versions:

<img width="274" alt="Screenshot 2022-12-12 at 08 39 42" src="https://user-images.githubusercontent.com/15089053/206988622-621b09f5-b203-4134-b33c-015713f2a264.png">

I have also tested with 4.0.0, same result.

**Comment by adrienharnay** [comment]
Hello, have you had a chance to look at the error? Thanks in advance @roginfarrer

**Comment by roginfarrer** [comment]
I've briefly looked at it and I can replicate, but I'm not 100% sure why that's happening. I have a major refactor ongoing in #122, and I'm hoping this issue resolves itself

**Comment by roginfarrer** [comment]
I'm not sure about the React version error, but I was able to reimplement this sandbox with Vite, and everything looked okay with me. Maybe something to do with CRA?

**Comment by adrienharnay** [comment]
4.0.0 does not seem to be released on npm

**Comment by roginfarrer** [comment]
The library was refactored and is now published under `@collapsed/react` https://github.com/roginfarrer/collapsed/releases/tag/%40collapsed%2Freact%404.0.0

**Comment by roginfarrer** [comment]
[NPM](https://www.npmjs.com/package/@collapsed/react)

heads up that I'm currently working through some bugs from the refactor right now, so it's not 100% ready. It may work for you, though.

**Comment by roginfarrer** [comment]
@adrienharnay can you try this version: `@collapsed/react@4.1.0-experimental.79f518c`

**Comment by adrienharnay** [comment]
Hi, I tried the version and everything is going well. When are you planning on deprecating the old package and switching to the new one?
