### ISSUE TITLE
New version doesn't toggle

### ISSUE THREAD

**Issue by razzeee** [roginfarrer/collapsed#132]
I've tried to migrate to the new version here https://github.com/razzeee/website/commit/cbde5bcf0427b4a8aac70f5b3f3895368b954503

But it seems like I'm missing something, as clicking the toggle buttons does nothing. In fact it seems like all properties end up `undefined` or as empty functions.

**Comment by roginfarrer** [comment]
It's possible that all of the transition related css classes on the element is disrupting the animation. I'm not sure about the undefined functions though. Can you create a sandbox that reproduces the issue?

**Comment by razzeee** [comment]
Not sure, when I'll find time for that.

**Comment by razzeee** [comment]
It seems like 

```
ref={ref}
```

is somehow colliding with 

```
{...getCollapseProps()}
```

As soon as I remove the ref it starts working. But I need that to calculate the scrollheight and figure out, if I want to show the collapse button/fade the collapsible content.

**Comment by 7iomka** [comment]
> It seems like
> 
> ```
> ref={ref}
> ```
> 
> is somehow colliding with
> 
> ```
> {...getCollapseProps()}
> ```
> 
> As soon as I remove the ref it starts working. But I need that to calculate the scrollheight and figure out, if I want to show the collapse button/fade the collapsible content.

ref.ts
```
import * as React from 'react';

type PossibleRef<T> = React.Ref<T> | undefined;

type ComposeRefCallback<T> = (node: T) => void;

/**
 * Set a given ref to a given value
 * This utility takes care of different types of refs: callback refs and RefObject(s)
 */
const setRef = <T>(ref: PossibleRef<T>, value: T) => {
  if (typeof ref === 'function') {
    ref(value);
  } else if (ref !== null && ref !== undefined) {
    // eslint-disable-next-line no-param-reassign
    (ref as React.MutableRefObject<T>).current = value;
  }
};

/**
 * A utility to compose multiple refs together
 * Accepts callback refs and RefObject(s)
 */
const composeRefs = <T>(...refs: PossibleRef<T>[]): ComposeRefCallback<T> => {
  return (node: T): void => refs.forEach((ref) => setRef(ref, node));
};

/**
 * A custom hook that composes multiple refs
 * Accepts callback refs and RefObject(s)
 */
const useComposedRefs = <T>(...refs: PossibleRef<T>[]): ComposeRefCallback<T> => {
  // eslint-disable-next-line react-hooks/exhaustive-deps
  return React.useCallback(composeRefs(...refs), refs);
};

export { composeRefs, useComposedRefs };

```

Usage: `useComposedRefs(getCollapseProps().ref, ref))`

**Comment by roginfarrer** [comment]
Hey there, I'm sorry, there were some significant issues I missed in the refactor. I've done a bit of a rewrite. Can you try this version? `@collapsed/react@4.1.0-experimental.79f518c`

**Comment by razzeee** [comment]
Hrm, doesn't seem to help, did I miss something? https://github.com/flathub/website/commit/8e4ac950dae534f81bc734f285116cd8c9be1dd9

**Comment by roginfarrer** [comment]
> It seems like
> 
> ```
> ref={ref}
> ```
> 
> is somehow colliding with
> 
> ```
> {...getCollapseProps()}
> ```
> 
> As soon as I remove the ref it starts working. But I need that to calculate the scrollheight and figure out, if I want to show the collapse button/fade the collapsible content.

@razzeee Yes, you're overriding the ref handler returned by `getCollapseProps`. If you need to access the ref of the element, pass your ref to `getCollapseProps`:

```typescript
function Collapse() {
  const myRef = useRef()
  const {getCollapseProps} = useCollapse()

  return (
    <div {...getCollapseProps({ref: myRef}) />
  )
}
```

`useCollapse` makes sure that the ref passed in is assigned as expected. This was the case in the previous version, as well.

**Comment by razzeee** [comment]
That seems to do the trick

**Comment by razzeee** [comment]
> This was the case in the previous version, as well.

Ah, you mean the previous 4.0 version not `react-collapsed`. That's likely why it didn't work and we ended up here.
It did work fine with the `react-collasped` named lib.

Anyway here's the changelog of our successful update:
https://github.com/flathub/website/pull/1275/files
