### ISSUE TITLE
Incorrect peer dependency

### ISSUE THREAD

**Issue by Qudusayo** [roginfarrer/collapsed#136]
Running into build error deploying to Cloudflare.
> react-collapsed@3.6.0" has incorrect peer dependency "react@^16.8 || ^17".

Tried downgrading react-version, got: 
> Error: Next.js requires react >= 18.2.0 to be installed.
> next@13.1.5" has incorrect peer dependency "react@^18.2.0".

**Comment by aulonm** [comment]
Downgrade to react-collapsed@3.5.0. 3.6.0 removed react 18 support

**Comment by roginfarrer** [comment]
added support for React 18 in react-collapsed v4.0.1
