### ISSUE TITLE
SSR usage - prevent initially display if not expanded by default 

### ISSUE THREAD

**Issue by 7iomka** [roginfarrer/collapsed#138]
Hi.
I use next.js
On first render I see my collapse content opened before styles was applied.
To fix that, I need to manually setup like this one

```
    // defaultExpanded is prop from parent component
 
    const { getCollapseProps, getToggleProps, isExpanded } = useCollapse({
      defaultExpanded,
    });

    const { style, ...restCollapseProps } = getCollapseProps();

    const ssrCollapseProps = {
      style: { display: !defaultExpanded ? 'none' : undefined, ...style },
      ...restCollapseProps,
    };

```

Why just not to do this internally?
For uncontrolled version - as I did above (check `defaultExpanded`)
For controlled - similar way (check `isExpanded`)

Many thanks for awesome lib!

**Comment by roginfarrer** [comment]
I've done a bit of a rewrite to address a bunch of React issues. Can you try this version? `@collapsed/react@4.1.0-experimental.79f518c`

**Comment by 7iomka** [comment]
> I've done a bit of a rewrite to address a bunch of React issues. Can you try this version? `@collapsed/react@4.1.0-experimental.79f518c`

In this version 
On first render I see my collapse content is also opened before styles was applied.
Unlike the previous version, now nothing happens after rendering, despite the fact that it is expected that the styles will be applied to hide the content. Only after a click will the content be hidden and revealed.

Therefore, my suggestion still stands
Both versions have wrong logic.

**Comment by 7iomka** [comment]
Even I would say that the experimental version is worse than the stable version, because in the stable version you can get what you want, but in the experimental version you can't, because probably the styles are overwritten, and workaround that I write not working

**Comment by roginfarrer** [comment]
I cannot reproduce. Can you share an a codesandbox that reproduces this?

**Comment by 7iomka** [comment]
> useCollapse

https://codesandbox.io/s/reverent-chihiro-gncl9s?file=/pages/index.tsx

For see in action I would recommend to open url of codesanbox site in a new tab
Like this https://gncl9s.sse.codesandbox.io

To understand why this happens is very simple - because on the server initially content that should be invisible is rendered without display: none.
My workaround does this.

**Comment by kostia1st** [comment]
I can confirm that the issue existed in `4.0.1`.

I checked the proposed `4.1.0-experimental.79f518c` version - and it does work right.

Seems like the current `react-collapsed` of version `4.1.2` have it working right as well. Thus the issue in non-existent at this point.
