### ISSUE TITLE
Safari 13 support, or at least graceful error handling?

### ISSUE THREAD

**Issue by kostia1st** [roginfarrer/collapsed#152]
Currently, in Safari 13 react-collapsed generates an error
```
TypeError: mediaQueryList.addEventListener is not a function. 
(In 'mediaQueryList.addEventListener("change", listener)', 'mediaQueryList.addEventListener' is undefined)
```

I seem to have managed to track it down to
```ts
function usePrefersReducedMotion() {
  const [prefersReducedMotion, setPrefersReducedMotion] = useState2(false);
  useEffect3(() => {
    const mediaQueryList = window.matchMedia(QUERY);
    setPrefersReducedMotion(mediaQueryList.matches);
    const listener = (event) => {
      setPrefersReducedMotion(event.matches);
    };
    mediaQueryList.addEventListener("change", listener);
    return () => {
      mediaQueryList.removeEventListener("change", listener);
    };
  }, []);
  return prefersReducedMotion;
}
```

**Comment by kostia1st** [comment]
Just a kind reminder - will this issue be fixed?

PS: PRs for the repo aren't going anywhere either. And I personally don't like the idea of forking the repo just for the purpose of one fix, losing any potential future maintenance benefits. Hence the question

**Comment by roginfarrer** [comment]
Hey there, a PR is welcome. I think it might be `addListener` for older browsers?

**Comment by kostia1st** [comment]
I'm very sorry, I hurried up and made a mistake.
Please consider the newer PR
